### ISSUE TITLE
Unknown Exception. Exception Returned Null.

### ISSUE THREAD

**Issue by aANKFcrkfR** [DraxCodes/Party-Bot#11]
The bot is randomly leaveing and it is displaying in the console "Unknown Exception. Exception Returned Null.".

The error is coming from "Gateway".
![image](https://user-images.githubusercontent.com/61119347/79635394-4234bd80-8179-11ea-8d10-82d0a9f95b7d.png)
 I dont have the knowledge to fix it X|.

**Comment by DraxCodes** [comment]
I am not able to reproduce this issue locally with the current version of PartyBot.
Very unsure as to what may be causing it.

Can you provide any more info on when this happens or if it happens when using a certain bot command.

**Comment by danielriddell21** [comment]
I get this issue, too. @DraxCodes I can give you some information if you want

**Comment by DraxCodes** [comment]
> I get this issue, too. @DraxCodes I can give you some information if you want
> 

Sure, more information would be desirable.

**Comment by danielriddell21** [comment]
When the discord sends a reconnection request the bot will reconnect. But when the request comes in, for some reason the client throws a null error, responding with the 'Unknown Exception. Exception Returned Null'
