### ISSUE TITLE
Victoria keep trying to connect and eventually times out

### ISSUE THREAD

**Issue by Nights87** [DraxCodes/Party-Bot#13]
Hi,

Bot looks great, but having a minor issue, potentially I've missed something.

![image](https://user-images.githubusercontent.com/14832217/106444729-1b056d80-64b9-11eb-8132-267648930d70.png)

Looks like victoria cant connect and eventually gives up.
Any ideas?

**Comment by gsorensen** [comment]
Hi, I was setting up this example too, and the bot does not set up LavaLink itself.

Therefore, you need
1) Lavalink (and JDK 14)
2) application.yml which has the Lavalink parameters 

and then you need to run Lavalink with java -jar Lavalink.jar prior to running your bot.

**Comment by ProjektCode** [comment]
Hey, I'm having the same issue. Did you manage to get this fixed?
