### ISSUE TITLE
Still works at 2024?

### ISSUE THREAD

**Issue by gumbarros** [DraxCodes/Party-Bot#18]
Title

**Comment by julianoBRL** [comment]
i think it works but with a lot of setup, i would recommend moving to node.js since it is more updated and have a more active community. i'm also an active bot developer with node.js and also tried with this and it dont have all the libs to do cool things with all that discord have to offer.

**Comment by gumbarros** [comment]
Bruh, I was looking forward to this for being in .NET :(
