### ISSUE TITLE
Error after following the Forking instructions

### ISSUE THREAD

**Issue by theADAMJR** [DraxCodes/Party-Bot#5]
Error on Discord:

> ERROR OCCURED FROM - Music, Join/Play
> Error Deaitls: 
> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
> at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
> --- End of inner exception stack trace ---
> at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
> at System.Threading.Tasks.ValueTask1.get_Result()
> at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> at System.Threading.Tasks.ValueTask1.get_Result()
> at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask1 creationTask)
> at System.Threading.Tasks.ValueTask1.get_Result()
> at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
> at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
> at Victoria.LavaNode.ResolveRequestAsync(String query)
> at PartyBot.Services.AudioService.JoinOrPlayAsync(SocketGuildUser user, IMessageChannel textChannel, UInt64 guildId, String query) in C:\Users\user\Documents\Visual Studio 2015\Projects\Party-Bot\PartyBot\Services\AudioService.cs:line 79

**Comment by DraxCodes** [comment]
Sorry this also requires Lavalink installed on your PC. Please Install it to have the bot working.
