### ISSUE TITLE
I cant play music

### ISSUE THREAD

**Issue by aANKFcrkfR** [DraxCodes/Party-Bot#8]
When i try to play music i get this:
![image](https://user-images.githubusercontent.com/61119347/78215058-51e8ac80-74bf-11ea-9cba-47b8cf82e047.png)
I get this in LavaLink
![image](https://user-images.githubusercontent.com/61119347/78215120-747ac580-74bf-11ea-9f6e-b684c7539bd7.png)
Any idea why?

**Comment by DraxCodes** [comment]
Lavalink issue, should now be resolved as of the latest build of PartyBot.
